function   t=VisualizeModes_3D_side_top(meshData, nodalData, deformationData, phasor, XLimits, YLimits, ZLimits,   DefScaleFactor, ColorLimits)

    phaseData = phasor;




% Create PDE result visualization

t = tiledlayout(3,1,'TileSpacing','Compact','Padding','Compact'); 
    
nexttile

    
    resultViz = pdeviz(meshData, abs(real(nodalData*phaseData)), ...
            "MeshVisible", 'on', ...
            "DeformationData",deformationData*phaseData, ...    % --> displacement
            "DeformationScaleFactor",DefScaleFactor, ...                
            "AxesVisible",true, ...
            "XLabel", 'x', "YLabel", 'y', "ZLabel", 'z', ...
            "ColorbarVisible",false, ...
            "ColorLimits",ColorLimits ...
        );
        resultViz.XLimits = XLimits;
        resultViz.YLimits = YLimits;
        resultViz.ZLimits = ZLimits;
        % resultViz.View = angles;

    
   
nexttile
     resultViz2 = pdeviz(meshData, abs(real(nodalData*phaseData)), ...
            "MeshVisible", 'on', ...
            "DeformationData",deformationData*phaseData, ...    % --> displacement
            "DeformationScaleFactor",DefScaleFactor, ...                
            "AxesVisible",true, ...
            "XLabel", 'x',   "ZLabel", 'z', ...
            "ColorbarVisible",false, ...
            "ColorLimits",ColorLimits ...
        );
        resultViz2.XLimits = XLimits;
        resultViz2.YLimits = YLimits;
        resultViz2.ZLimits = ZLimits;
        resultViz2.View = [0 0];

nexttile
     resultViz3 = pdeviz(meshData, abs(real(nodalData*phaseData)), ...
            "MeshVisible", 'on', ...
            "DeformationData",deformationData*phaseData, ...    % --> displacement
            "DeformationScaleFactor",DefScaleFactor, ...                
            "AxesVisible",true, ...
            "XLabel", 'x', "YLabel", 'y',   ...
            "ColorbarVisible",false, ...
            "ColorLimits",ColorLimits ...
        );
        resultViz3.XLimits = XLimits;
        resultViz3.YLimits = YLimits;
        resultViz3.ZLimits = ZLimits;
        resultViz3.View = [0 90];
